version: '2'
services:
    kayhianmongoaccess-app:
        image: kayhianmongoaccess
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kayhianmongoaccess-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=kayhianMongoAccess
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=kayhianmongoaccess-elasticsearch:9300
        ports:
            - 8080:8080
    kayhianmongoaccess-mongodb:
        extends:
            file: mongodb.yml
            service: kayhianmongoaccess-mongodb
    kayhianmongoaccess-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: kayhianmongoaccess-elasticsearch
